### ISSUE TITLE
The schema.json is missing in the package which causes json_validate() to fail

### ISSUE THREAD

**Issue by bitdot101** [O-X-L/python3-nftables#1]
The original [setup.cfg](http://git.netfilter.org/nftables/tree/py/setup.cfg#n24) has `schema.json` in the package_data. However the setup.py in the repo does not have that.

**Comment by ansibleguy** [comment]
Should now be included using the [MANIFEST.in](https://packaging.python.org/en/latest/guides/using-manifest-in/)
Can you verify that?

**Comment by bitdot101** [comment]
Looks good now. Thanks for quick response!
